# Generated by Django 5.2.5 on 2025-09-04 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=9)),
                ('billing_cycle_days', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, help_text='List or map of features included', null=True)),
                ('active', models.BooleanField(default=True)),
                ('external_plan_id', models.CharField(blank=True, help_text='Plan id on payment gateway', max_length=255)),
            ],
            options={
                'ordering': ('price_per_month',),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('external_subscription_id', models.CharField(blank=True, help_text='ID in payment gateway', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date',),
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
