# Generated by Django 5.2.5 on 2025-09-04 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_source', models.CharField(default='website', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BlueWave Solutions', max_length=100)),
                ('site_tagline', models.CharField(default='Sustainable Water Solutions for a Better Tomorrow', max_length=200)),
                ('contact_email', models.EmailField(default='contact@bluewave-solutions.com', max_length=254)),
                ('support_email', models.EmailField(default='support@bluewave-solutions.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('company_address', models.TextField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0875, help_text='Default tax rate (e.g., 0.0875 for 8.75%)', max_digits=5)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=25.0, help_text='Default shipping cost', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500.0, help_text='Free shipping above this amount', max_digits=10)),
                ('co2_reduction_per_gallon', models.DecimalField(decimal_places=4, default=2.3, help_text='CO2 reduction in kg per gallon processed', max_digits=8)),
                ('total_gallons_processed', models.BigIntegerField(default=0, help_text='Total gallons processed by all units')),
                ('total_co2_saved', models.DecimalField(decimal_places=2, default=0, help_text='Total CO2 saved in kg', max_digits=12)),
                ('api_base_url', models.URLField(default='https://api.bluewave-solutions.com/v1/')),
                ('api_rate_limit', models.IntegerField(default=1000, help_text='API calls per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('orders_today', models.IntegerField(default=0)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('products_sold_today', models.IntegerField(default=0)),
                ('total_products_sold', models.IntegerField(default=0)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('new_subscriptions_today', models.IntegerField(default=0)),
                ('subscription_revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gallons_processed_today', models.IntegerField(default=0)),
                ('co2_saved_today', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'System Stats',
                'verbose_name_plural': 'System Stats',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
